### ISSUE TITLE
The opening page knows Paul before he has signed in

### ISSUE THREAD

**Issue by TKostrzewski** [FACxBeamery/project-week-7-joao-toni#22]
I understand you have dummy data in at the moment but something to consider for later. Even before I am able to sign in, the tool has greeted me. How does it know who I am?

However! It's really cool that you have a sign in page and means your tool scales well and has been well thought out!

**Comment by Joaoviana** [comment]
Paul is our set persona. Will add a form before displaying the greeting message :) thank you!
