### ISSUE TITLE
Cards changing size

### ISSUE THREAD

**Issue by thomas-galligan** [FACxBeamery/project-week-7-joao-toni#23]
When you mark an item as complete, the card changes size. This seems to happen because the button and "in progress" marker change change size, and the card is forced to compensate. I tried setting the card width to 60vw and it seems to fix the issue. 
<img width="723" alt="Screenshot 2019-10-25 at 10 28 16" src="https://user-images.githubusercontent.com/36141893/67560141-2a243a00-f712-11e9-9de7-521d852c6b1f.png">

**Comment by Joaoviana** [comment]
It's fixed now! thank you for the suggestion!
