### ISSUE TITLE
Potential for component nesting

### ISSUE THREAD

**Issue by teenie-quaggard** [FACxBeamery/project-week-7-joao-toni#35]
There are many ways to structure a Component folder, some people (like me) prefer to keep component file flattened (I don't use any nested folders, but just use file names as an organising feature).

That said, many people prefer to nest smaller component within the larger one. One potential for this might be to move your TaskOverviewRow into your TaskOverviewList as one helps build up the other. 

That said, avoid too much nesting! With React, you don't want to go more than three layers deep into a file struture.

**Comment by Joaoviana** [comment]
Thank you for the explanation! Will nest those in a bit!
