### ISSUE TITLE
Another opportunity to decompose into components

### ISSUE THREAD

**Issue by arrested-developer** [FACxBeamery/project-week-7-joao-toni#43]
https://github.com/FACxBeamery/project-week-7-joao-toni/blob/1705a12c3f74c107075acf65d86cf2d57abf5d9d/src/components/FormField/FormField.js#L15-L42

Any time you're assigning a chunk of JSX to a variable, consider whether you could assign it to a component function instead. You could break out these lines into a subcomponent within this file, which you can pass different props depending on how you want it to render.

**Comment by Joaoviana** [comment]
Thank you for the clarification, wasn't sure what to do here!
