### ISSUE TITLE
Due date form input

### ISSUE THREAD

**Issue by marthaklambert** [FACxBeamery/project-week-7-joao-toni#57]
On your due date input only a time is allowed. The word date is a bit confusing here, but also perhaps a user would want to specify a date/day of the week aswell as a time. Is there any way you could add a dropdown to only allow valid inputs and let the user do less work?

<img width="983" alt="Screenshot 2019-11-01 at 10 33 45" src="https://user-images.githubusercontent.com/44317394/68019339-5bad8000-fc93-11e9-8fb1-54784e8570ee.png">

**Comment by Joaoviana** [comment]
Absolutely Martha. 

Will have a select dropdown for the day of the week. 
And probably two inputs for time of the event: [HH] : [MM] like this
