### ISSUE TITLE
You can use body parser as common middleware

### ISSUE THREAD

**Issue by arrested-developer** [FACxBeamery/project-week-7-joao-toni#82]
https://github.com/FACxBeamery/project-week-7-joao-toni/blob/f4748433b27df2422526f81753f1f2a88d904a5c/server/router.js#L16

Is there a reason why you've applied body parser to a specific route? It should do no harm to use it as common middleware, e.g. `app.use(bodyParser.json())`

More info here on either using as common middleware, and using on specific routes, e.g. to handle JSON -

https://github.com/expressjs/body-parser#express-route-specific

**Comment by Joaoviana** [comment]
We were just testing if the custom middleware was working. We're working on another branch and we have set up the server to use the bodyparser 'globally' 😄
