### ISSUE TITLE
eslint setup looks good!

### ISSUE THREAD

**Issue by arrested-developer** [FACxBeamery/project-week-7-joao-toni#83]
How have you found working with eslint? Did you add any rules to the setup?

**Comment by Joaoviana** [comment]
`no-multiple-empty-lines: [2, { max: 2, maxEOF: 1 }]`
for no more than 2 consecutive empty lines
and only one 1 line allowed at the end of each file

`max-len: ["error", { code: 80 }]`
max length of code: 80 chars
