### ISSUE TITLE
mongo driver should already work with promises

### ISSUE THREAD

**Issue by arrested-developer** [FACxBeamery/project-week-7-joao-toni#84]
https://github.com/FACxBeamery/project-week-7-joao-toni/blob/f4748433b27df2422526f81753f1f2a88d904a5c/server/database/queries/addTask.js#L1-L10

A couple of things here - are you querying for the collection in your handler? Why is the query split into two parts like this. It makes your handler and query tightly coupled, and you won't be able to change the implementation of your database (say by changing to SQL) without changing both the handler and the query. Try to keep your query completely independent of your handler.

Second, I think the mongo query should already work as a promise, so returning `tasks.insertOne...` should be sufficient, without wrapping it in a promise.

**Comment by Joaoviana** [comment]
https://github.com/FACxBeamery/project-week-7-joao-toni/pull/98/commits/27e79ce48997fe46e31c474f9073cf3016b3dc4f
