### ISSUE TITLE
Use async / await

### ISSUE THREAD

**Issue by arrested-developer** [FACxBeamery/project-week-7-joao-toni#86]
https://github.com/FACxBeamery/project-week-7-joao-toni/blob/f4748433b27df2422526f81753f1f2a88d904a5c/server/handlers/UsersCollection/createUser.js#L1-L12

```javascript
 const createUser = async (req, res) => { 
     try {
         const db = await getDB(); 
         const result = await addUser(db.collection("users")) 
         res.status(200).json(result)
     } catch (err) {
         res.status(500).send(err)
     }
 }; 
```

**Comment by arrested-developer** [comment]
Try to use async await across your handlers. Also use the correct status code for your error

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status

**Comment by Joaoviana** [comment]
https://github.com/FACxBeamery/project-week-7-joao-toni/pull/98/commits/178a63cab62c2d126a7bcc5b2722566616b6255c
