### ISSUE TITLE
Use descriptive, imperative commit messages

### ISSUE THREAD

**Issue by arrested-developer** [FACxBeamery/project-week-7-joao-toni#89]
<img width="334" alt="Screenshot 2019-11-08 at 10 45 30" src="https://user-images.githubusercontent.com/28838993/68470962-10581c00-0215-11ea-88f8-e5c4a17b6def.png">

The above, in particular, is not good git practice 😉

A commit should make sense when prefixed with "If applied, this commit will..."

This article goes into some depth about commits and is well worth a read. This is very important when you're working with a team and these good habits are worth developing asap.

https://chris.beams.io/posts/git-commit/

**Comment by Joaoviana** [comment]
Thank you for the  "If applied, this commit will..." 'mental' prefix! That will help me more from now on :)
