### ISSUE TITLE
Is your nesting a little OTT?

### ISSUE THREAD

**Issue by thomas-galligan** [FACxBeamery/project-week-7-joao-toni#92]
<img width="151" alt="Screenshot 2019-11-08 at 10 52 55" src="https://user-images.githubusercontent.com/36141893/68471385-fff47100-0215-11ea-81d4-34022c5e2696.png">

**Comment by Joaoviana** [comment]
We have 2 different collections: tasks & users. I believe some db queries could be detached from a specific db collection, but there are other db queries that do specific things for a specific collection. 
We'll be working on that, but for now this folder structure makes sense that's all :)
