### ISSUE TITLE
You have some handlers that invoke functions that aren't defined/imported 

### ISSUE THREAD

**Issue by thomas-galligan** [FACxBeamery/project-week-7-joao-toni#93]
<img width="831" alt="Screenshot 2019-11-08 at 10 54 34" src="https://user-images.githubusercontent.com/36141893/68471462-2c0ff200-0216-11ea-85a4-c7ec27804b26.png">

**Comment by Joaoviana** [comment]
thank you for pointing this out. Will remove any unused handlers!
