### ISSUE TITLE
A series of callback functions after a POST request.

### ISSUE THREAD

**Issue by TKostrzewski** [FACxBeamery/project-week-7-joao-toni#94]
I'm curious as to why you have included your callbacks in an array, as well as in a series? Could you explain what happens when I run a POST request with the "/tasks" endpoint please?

```
router.post("/tasks", [taskValidator(true), bodyParser], createTask);
```

**Comment by Joaoviana** [comment]
the second argument in that post request is an array of middleware. `bodyparser` as been set to be used in the server, and not specifically for this route
